--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document (
    id integer NOT NULL,
    name character varying(300) NOT NULL,
    industry_id integer,
    role_id integer
);


ALTER TABLE public.document OWNER TO postgres;

--
-- Name: document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.document ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gas_form; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gas_form (
    id integer NOT NULL,
    diameter character varying(50),
    diameter2 character varying(50),
    cost character varying(50),
    duration character varying(50),
    project_id integer,
    is_signed boolean DEFAULT false
);


ALTER TABLE public.gas_form OWNER TO postgres;

--
-- Name: gas_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gas_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gas_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.industry (
    id integer NOT NULL,
    name character varying(50)
);


ALTER TABLE public.industry OWNER TO postgres;

--
-- Name: industry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.industry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    industry_id integer NOT NULL,
    designer_id integer,
    developer_id integer,
    date_created date DEFAULT now() NOT NULL,
    created_by integer
);


ALTER TABLE public.project OWNER TO postgres;

--
-- Name: project_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_document (
    id integer NOT NULL,
    project_id integer NOT NULL,
    document_id integer NOT NULL,
    is_necessary boolean DEFAULT false NOT NULL,
    is_signed boolean DEFAULT false NOT NULL,
    sign_date date,
    date_created date DEFAULT now() NOT NULL
);


ALTER TABLE public.project_document OWNER TO postgres;

--
-- Name: project_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_document ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.project_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    login character varying(50) NOT NULL,
    encrypted_password character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(12) NOT NULL,
    role_id integer,
    data json
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: water_form; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.water_form (
    id integer NOT NULL,
    diameter character varying(50),
    performance character varying(50),
    kns character varying(50),
    cost character varying(50),
    duration character varying(50),
    project_id integer,
    is_signed boolean DEFAULT false
);


ALTER TABLE public.water_form OWNER TO postgres;

--
-- Name: water_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.water_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.water_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: document; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.document (id, name, industry_id, role_id) FROM stdin;
3	Согласованный ситуационный план (М1:10000 или М1:25000) с нанесением источников воды (скважин, родников и т.п.), существующих водонапорных башен, предполагаемой трассой водопровода и места врезки в существующую сеть	2	1
2	Акт обследования и выбор места под проектируемую скважину	2	1
1	Акт обследования и выбора трассы сетиводоснабжения	2	1
5	Технические условия на водоснабжение	2	1
7	Градостроительный план земельного участка	2	1
15	Технические условия на присоединение к газораспределительной сети (№, дата, срок действий Технических условий)	3	1
14	Ситуационный план (утвержденный исполкомом)	3	1
13	Задание на проектирование	3	1
12	Письмо-обращение на имя Президента,Премьер-Министра, Минстрой РТ	3	1
16	Технический паспорт (план БТИ) объекта СКБ	3	1
20	Согласование посадки котельной	3	1
19	Технические условия на сети электроснабжение, водоснабжения, водоотведения при установке БМК	3	1
18	АКТ обследования объекта	3	1
17	Технический паспорт (план БТИ) существующей котельной	3	1
6	Технические условия на электроснабжение (для насосной станции первого или второго подъема)	2	1
11	Сведения о наличие водозаборных скважин (родников) на территории хозяйства	2	1
10	Заключение Органа Роспотребнадзора санитарно-эпидемиологической службы по отводу земельного участка и результат радиационного обследования	2	1
9	Документ, подтверждающий проведение межевания с присвоением кадастрового номера земельного участка под строительство водопровода и сооружений на нем	2	1
8	Справка согласования с собственниками земельных участков	2	1
4	План населённого пункта в М 1:1000 или М 1:500 топографическая съемка	2	1
21	Смета на ПиР	1	3
22	График проектирования	1	3
\.


--
-- Data for Name: gas_form; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gas_form (id, diameter, diameter2, cost, duration, project_id, is_signed) FROM stdin;
6	1200	1200	8901200001	15	3	f
\.


--
-- Data for Name: industry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.industry (id, name) FROM stdin;
1	Любой
2	Водоснабжение
3	Газификация
\.


--
-- Data for Name: project; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project (id, name, industry_id, designer_id, developer_id, date_created, created_by) FROM stdin;
5	Water project - 3	2	4	3	2022-11-14	2
8	test gas project	3	4	6	2022-11-17	2
9	test gas project - 3	3	5	6	2022-11-17	2
2	Water project - 1	2	4	3	2022-11-13	7
3	Gas project - 1	3	4	6	2022-11-13	2
4	Water project - 2	2	5	3	2022-11-13	7
\.


--
-- Data for Name: project_document; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project_document (id, project_id, document_id, is_necessary, is_signed, sign_date, date_created) FROM stdin;
5	5	6	f	f	\N	2022-11-14
6	3	21	f	f	\N	2022-11-17
7	3	22	f	t	2022-11-17	2022-11-17
2	2	3	f	f	\N	2022-11-13
17	8	15	f	f	\N	2022-11-17
18	8	14	f	f	\N	2022-11-17
19	8	13	f	f	\N	2022-11-17
20	8	12	f	f	\N	2022-11-17
21	8	16	f	f	\N	2022-11-17
22	8	20	f	f	\N	2022-11-17
23	8	19	f	f	\N	2022-11-17
24	8	18	f	f	\N	2022-11-17
25	8	17	f	f	\N	2022-11-17
26	8	21	f	f	\N	2022-11-17
27	8	22	f	f	\N	2022-11-17
3	2	9	t	f	\N	2022-11-13
4	2	21	t	f	\N	2022-11-13
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role (id, name) FROM stdin;
1	Застройщик
2	Заказчик
3	Проектировщик
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (id, login, encrypted_password, email, phone_number, role_id, data) FROM stdin;
4	designer	R\\j��؁ �A�����*�[6�ˆ.:�#����	designer@mail.ru	12312312	3	{"Director":"Director Name","LeadEngineer":"Engineer name","Ogrn":"1234567891011","Tin":"1234567890","Kpp":"123456789","Address":"Ulitsa Gogolya","Name":"Designer number one"}
2	customer	R\\j��؁ �A�����*�[6�ˆ.:�#����	customer@gmail.com	89172400986	2	{"IndustryType":3,"Department":"Some department here","Name":"Customer number one!"}
3	developer	R\\j��؁ �A�����*�[6�ˆ.:�#����	developer@mail.ru	123124	1	{"ExecutiveDirector":"Director Name","Ogrn":"1234567891011","Tin":"1234567890","Kpp":"123456789","Address":"Ulitsa Pushkina","Name":"Developer number one"}
5	designer1	R\\j��؁ �A�����*�[6�ˆ.:�#����	designer1@mail.ru	1234124124	3	{"Director":"Director","LeadEngineer":"Engineer","Ogrn":"1110987654321","Tin":"0987654321","Kpp":"987654321","Address":"Ulitsa Bari Galeeva","Name":"Designer number two"}
6	developer1	R\\j��؁ �A�����*�[6�ˆ.:�#����	developer1@mail.ru	1231243124	1	{"ExecutiveDirector":null,"Ogrn":null,"Tin":null,"Kpp":null,"Address":null,"Name":"Developer number two"}
7	customer1	R\\j��؁ �A�����*�[6�ˆ.:�#����	customer1@mail.ru	123124	2	{"IndustryType":2,"Department":"Department","Name":"Customer number two"}
\.


--
-- Data for Name: water_form; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.water_form (id, diameter, performance, kns, cost, duration, project_id, is_signed) FROM stdin;
1	EQW5	432RFE	GDFGVQ	VDFGBG	VFDGFH	2	f
4	123	123	123	123	132	5	t
\.


--
-- Name: document_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.document_id_seq', 22, true);


--
-- Name: gas_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gas_form_id_seq', 6, true);


--
-- Name: industry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.industry_id_seq', 3, true);


--
-- Name: project_document_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.project_document_id_seq', 27, true);


--
-- Name: project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.project_id_seq', 9, true);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 3, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 7, true);


--
-- Name: water_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.water_form_id_seq', 4, true);


--
-- Name: document document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);


--
-- Name: gas_form gas_form_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gas_form
    ADD CONSTRAINT gas_form_pkey PRIMARY KEY (id);


--
-- Name: industry industry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.industry
    ADD CONSTRAINT industry_pkey PRIMARY KEY (id);


--
-- Name: project_document project_document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_document
    ADD CONSTRAINT project_document_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: water_form water_form_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.water_form
    ADD CONSTRAINT water_form_pkey PRIMARY KEY (id);


--
-- Name: document document_industry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industry(id) ON UPDATE CASCADE;


--
-- Name: document document_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: gas_form gas_form_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gas_form
    ADD CONSTRAINT gas_form_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project project_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- Name: project project_designer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_designer_id_fkey FOREIGN KEY (designer_id) REFERENCES public."user"(id);


--
-- Name: project project_developer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_developer_id_fkey FOREIGN KEY (developer_id) REFERENCES public."user"(id);


--
-- Name: project_document project_document_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_document
    ADD CONSTRAINT project_document_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);


--
-- Name: project_document project_document_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_document
    ADD CONSTRAINT project_document_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project project_industry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industry(id) ON UPDATE CASCADE;


--
-- Name: user user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: water_form water_form_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.water_form
    ADD CONSTRAINT water_form_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- PostgreSQL database dump complete
--

